blog/urls.py
from django.urls import path

from blog.views import BlogListView, BlogDetailView, CommentCreateView

app_name = 'blog'

urlpatterns = [
    path('<int:pk>/', BlogDetailView.as_view(), name='detail'),
    path('<int:pk>/comment/', CommentCreateView.as_view(), name='comment'),
    path('', BlogListView.as_view(), name='list'),
]

pages/urls.py
from django.urls import path

from pages.views import ContactCreateView, IndexTemplateView, AboutTemplateView

app_name = 'pages'

urlpatterns = [
    path('contact/', ContactCreateView.as_view(), name='contact'),
    path('about/', AboutTemplateView.as_view(), name='about'),
    path('', IndexTemplateView.as_view(), name='home'),
]

shop4/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path('products/', include('products.urls', namespace='products')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('', include('pages.urls', namespace='pages')),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/layouts/base.html
{% load static %}
<!DOCTYPE html>
<html lang="zxx">

<head>
    <meta charset="UTF-8">
    <meta name="description" content="Male_Fashion Template">
    <meta name="keywords" content="Male_Fashion, unica, creative, html">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Male-Fashion | Template</title>

    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css2?family=Nunito+Sans:wght@300;400;600;700;800;900&display=swap"
          rel="stylesheet">

    <!-- Css Styles -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/elegant-icons.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/nice-select.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/slicknav.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css">

    {% block extra_css %} {% endblock %}
</head>

<body>

{#<div id="preloader">#}
{#    <div class="loader"></div>#}
{#</div>#}


{% include 'layouts/header.html' %}

{#<!-- Map Begin -->#}
{#<div class="map">#}
{#    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d111551.9926412813!2d-90.27317134641879!3d38.606612219170856!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x54eab584e432360b%3A0x1c3bb99243deb742!2sUnited%20States!5e0!3m2!1sen!2sbd!4v1597926938024!5m2!1sen!2sbd"#}
{#            height="500" style="border:0;" allowfullscreen="" aria-hidden="false" tabindex="0"></iframe>#}
{#</div>#}
{#<!-- Map End -->#}

{% block content %}{% endblock %}


<!-- Search Begin -->
<div class="search-model">
    <div class="h-100 d-flex align-items-center justify-content-center">
        <div class="search-close-switch">+</div>
        <form class="search-model-form">
            <input type="text" id="search-input" placeholder="Search here.....">
        </form>
    </div>
</div>
<!-- Search End -->

{% include 'layouts/footer.html' %}

<!-- Js Plugins -->
<script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/jquery.nice-select.min.js' %}"></script>
<script src="{% static 'js/jquery.nicescroll.min.js' %}"></script>
<script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
<script src="{% static 'js/jquery.countdown.min.js' %}"></script>
<script src="{% static 'js/jquery.slicknav.js' %}"></script>
<script src="{% static 'js/mixitup.min.js' %}"></script>
<script src="{% static 'js/owl.carousel.min.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>

{% block extra_js %}{% endblock %}
</body>

</html>

templates/layouts/footer.html
{% load static %}
<!-- Footer Section Begin -->
<footer class="footer">
    <div class="container">
        <div class="row">
            <div class="col-lg-3 col-md-6 col-sm-6">
                <div class="footer__about">
                    <div class="footer__logo">
                        <a href="#"><img src="{% static 'img/footer-logo.png' %}" alt=""></a>
                    </div>
                    <p>The customer is at the heart of our unique business model, which includes design.</p>
                    <a href="#"><img src="{% static 'img/payment.png' %}" alt=""></a>
                </div>
            </div>
            <div class="col-lg-2 offset-lg-1 col-md-3 col-sm-6">
                <div class="footer__widget">
                    <h6>Shopping</h6>
                    <ul>
                        <li><a href="#">Clothing Store</a></li>
                        <li><a href="#">Trending Shoes</a></li>
                        <li><a href="#">Accessories</a></li>
                        <li><a href="#">Sale</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-lg-2 col-md-3 col-sm-6">
                <div class="footer__widget">
                    <h6>Shopping</h6>
                    <ul>
                        <li><a href="#">Contact Us</a></li>
                        <li><a href="#">Payment Methods</a></li>
                        <li><a href="#">Delivery</a></li>
                        <li><a href="#">Return & Exchanges</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-lg-3 offset-lg-1 col-md-6 col-sm-6">
                <div class="footer__widget">
                    <h6>NewLetter</h6>
                    <div class="footer__newslatter">
                        <p>Be the first to know about new arrivals, look books, sales & promos!</p>
                        <form action="#">
                            <input type="text" placeholder="Your email">
                            <button type="submit"><span class="icon_mail_alt"></span></button>
                        </form>
                    </div>
                </div>
            </div>
        </div>

    </div>
</footer>

<div class="search-model">
    <div class="h-100 d-flex align-items-center justify-content-center">
        <div class="search-close-switch">+</div>
        <form class="search-model-form">
            <input type="text" id="search-input" placeholder="Search here.....">
        </form>
    </div>
</div>

templates/layouts/header.html
{% load static %}
<!-- Offcanvas Menu Begin -->
<div class="offcanvas-menu-overlay"></div>
<div class="offcanvas-menu-wrapper">
    <div class="offcanvas__option">
        <div class="offcanvas__links">
            <a href="#">Sign in</a>
        </div>
        <div class="offcanvas__top__hover">
            <span>EN <i class="arrow_carrot-down"></i></span>
            <ul>
                <li>RU</li>
                <li>UZ</li>
            </ul>
        </div>
    </div>
    <div class="offcanvas__nav__option">
        <a href="#" class="search-switch"><img src="{% static 'img/icon/search.png' %}" alt=""></a>
        <a href="#"><img src="{% static 'img/icon/heart.png' %}" alt=""></a>
        <a href="#"><img src="{% static 'img/icon/cart.png' %}" alt=""> <span>0</span></a>
        <div class="price">$0.00</div>
    </div>
    <div id="mobile-menu-wrap"></div>
    <div class="offcanvas__text">
    </div>
</div>
<!-- Offcanvas Menu End -->

<!-- Header Section Begin -->
<header class="header">
    <div class="header__top">
        <div class="container">
            <div class="row">
                <div class="col-lg-6 col-md-7">
                    <div class="header__top__left">
                    </div>
                </div>
                <div class="col-lg-6 col-md-5">
                    <div class="header__top__right">
                        <div class="header__top__links">
                            <a href="#">Sign in</a>
                        </div>
                        <div class="header__top__hover">
                            <span>EN <i class="arrow_carrot-down"></i></span>
                            <ul>
                                <li>RU</li>
                                <li>UZ</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-lg-3 col-md-3">
                <div class="header__logo">
                    <a href="{% url 'pages:home' %}"><img src="{% static 'img/logo.png' %}" alt=""></a>
                </div>
            </div>
            <div class="col-lg-6 col-md-6">
                <nav class="header__menu mobile-menu">
                    <ul>
                        <li {% if request.path == '/' %}class="active" {% endif %} ><a href="{% url 'pages:home' %}">Home</a></li>
                        <li {% if request.path == '/poducts/' %}class="active"{% endif %}><a href="{% url 'products:list' %}">Products</a></li>
                        <li {% if request.path == '/blog/' %}class="active" {% endif %}><a href="{% url 'blog:list' %}">Blog</a></li>
                        <li{% if request.path == '/about/' %} class="active" {% endif %}><a href="{% url 'pages:about' %}">About</a></li>
                        <li {% if request.path == '/contact/' %}class="active" {% endif %} ><a href="{% url 'pages:contact' %}">Contact </a></li>
                    </ul>
                </nav>
            </div>
            <div class="col-lg-3 col-md-3">
                <div class="header__nav__option">
                    <a href="#" class="search-switch"><img src="{% static 'img/icon/search.png' %}" alt=""></a>
                    <a href="#"><img src="{% static 'img/icon/heart.png' %}" alt=""></a>
                    <a href="#"><img src="{% static 'img/icon/cart.png' %}" alt=""> <span>0</span></a>
                    <div class="price">$0.00</div>
                </div>
            </div>
        </div>
        <div class="canvas__open"><i class="fa fa-bars"></i></div>
    </div>
</header>
<!-- Header Section End -->

templates/layouts/product_block.html
{% load static %}
<div class="product__item {% if product.discount %}sale{% endif %} ">
    <div class="product__item__pic set-bg"
         data-setbg="{{ product.image.url }}">
        {% if product.is_discount %}
            <span class="label">Sale</span>
        {% endif %}
        {% if product.is_new %}
            <span style="background-color: white; color: #111"
                  class="label {% if product.discount %}mt-4{% endif %}">New</span>
        {% endif %}
        <ul class="product__hover">
            <li>
                <a href="#"><img src="{% static 'img/icon/heart.png' %}" alt=""></a>
            </li>

            <li>
                <a href="{% url 'products:detail' pk=product.pk %}"><img src="{% static 'img/icon/search.png' %}"
                                                                         alt=""></a>
            </li>
        </ul>
    </div>
    <div class="product__item__text">
        <h6>{{ product.title }}</h6>
        <a href="#" class="add-cart">+ Add To Cart</a>
        <div class="rating">
            <i class="fa fa-star-o"></i>
            <i class="fa fa-star-o"></i>
            <i class="fa fa-star-o"></i>
            <i class="fa fa-star-o"></i>
            <i class="fa fa-star-o"></i>
        </div>
        <h5>{{ product.get_price }}
            {% if product.is_discount %}
                <strike class="text-secondary">{{ product.price }}</strike>>{% endif %}
        </h5>
        <div class="product__color__select">
            <label for="pc-4">
                <input type="radio" id="pc-4">
            </label>
            <label class="active black" for="pc-5">
                <input type="radio" id="pc-5">
            </label>
            <label class="grey" for="pc-6">
                <input type="radio" id="pc-6">
            </label>
        </div>
    </div>
</div>

templates/layouts/shop_filter.html
<div class="shop__sidebar">
    <div class="shop__sidebar__search">
        <form action="#">
            <input type="text" placeholder="Search...">
            <button type="submit"><span class="icon_search"></span></button>
        </form>
    </div>
    <div class="shop__sidebar__accordion">
        <div class="accordion" id="accordionExample">
            <div class="card">
                <div class="card-heading">
                    <a data-toggle="collapse" data-target="#collapseOne">Categories</a>
                </div>
                <div id="collapseOne" class="collapse show" data-parent="#accordionExample">
                    <div class="card-body">
                        <div class="shop__sidebar__categories">
                            <ul class="nice-scroll">
                                <li><a href="#">Men (20)</a></li>
                                <li><a href="#">Women (20)</a></li>
                                <li><a href="#">Bags (20)</a></li>
                                <li><a href="#">Clothing (20)</a></li>
                                <li><a href="#">Shoes (20)</a></li>
                                <li><a href="#">Accessories (20)</a></li>
                                <li><a href="#">Kids (20)</a></li>
                                <li><a href="#">Kids (20)</a></li>
                                <li><a href="#">Kids (20)</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="card">
                <div class="card-heading">
                    <a data-toggle="collapse" data-target="#collapseTwo">Branding</a>
                </div>
                <div id="collapseTwo" class="collapse show" data-parent="#accordionExample">
                    <div class="card-body">
                        <div class="shop__sidebar__brand">
                            <ul>
                                <li><a href="#">Louis Vuitton</a></li>
                                <li><a href="#">Chanel</a></li>
                                <li><a href="#">Hermes</a></li>
                                <li><a href="#">Gucci</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="card">
                <div class="card-heading">
                    <a data-toggle="collapse" data-target="#collapseThree">Filter Price</a>
                </div>
                <div id="collapseThree" class="collapse show" data-parent="#accordionExample">
                    <div class="card-body">
                        <div class="shop__sidebar__price">
                            <ul>
                                <li><a href="#">$0.00 - $50.00</a></li>
                                <li><a href="#">$50.00 - $100.00</a></li>
                                <li><a href="#">$100.00 - $150.00</a></li>
                                <li><a href="#">$150.00 - $200.00</a></li>
                                <li><a href="#">$200.00 - $250.00</a></li>
                                <li><a href="#">250.00+</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="card">
                <div class="card-heading">
                    <a data-toggle="collapse" data-target="#collapseFour">Size</a>
                </div>
                <div id="collapseFour" class="collapse show" data-parent="#accordionExample">
                    <div class="card-body">
                        <div class="shop__sidebar__size">
                            <label for="xs">xs
                                <input type="radio" id="xs">
                            </label>
                            <label for="sm">s
                                <input type="radio" id="sm">
                            </label>
                            <label for="md">m
                                <input type="radio" id="md">
                            </label>
                            <label for="xl">xl
                                <input type="radio" id="xl">
                            </label>
                            <label for="2xl">2xl
                                <input type="radio" id="2xl">
                            </label>
                            <label for="xxl">xxl
                                <input type="radio" id="xxl">
                            </label>
                            <label for="3xl">3xl
                                <input type="radio" id="3xl">
                            </label>
                            <label for="4xl">4xl
                                <input type="radio" id="4xl">
                            </label>
                        </div>
                    </div>
                </div>
            </div>
            <div class="card">
                <div class="card-heading">
                    <a data-toggle="collapse" data-target="#collapseFive">Colors</a>
                </div>
                <div id="collapseFive" class="collapse show" data-parent="#accordionExample">
                    <div class="card-body">
                        <div class="shop__sidebar__color">
                            <label class="c-1" for="sp-1">
                                <input type="radio" id="sp-1">
                            </label>
                            <label class="c-2" for="sp-2">
                                <input type="radio" id="sp-2">
                            </label>
                            <label class="c-3" for="sp-3">
                                <input type="radio" id="sp-3">
                            </label>
                            <label class="c-4" for="sp-4">
                                <input type="radio" id="sp-4">
                            </label>
                            <label class="c-5" for="sp-5">
                                <input type="radio" id="sp-5">
                            </label>
                            <label class="c-6" for="sp-6">
                                <input type="radio" id="sp-6">
                            </label>
                            <label class="c-7" for="sp-7">
                                <input type="radio" id="sp-7">
                            </label>
                            <label class="c-8" for="sp-8">
                                <input type="radio" id="sp-8">
                            </label>
                            <label class="c-9" for="sp-9">
                                <input type="radio" id="sp-9">
                            </label>
                        </div>
                    </div>
                </div>
            </div>
            <div class="card">
                <div class="card-heading">
                    <a data-toggle="collapse" data-target="#collapseSix">Tags</a>
                </div>
                <div id="collapseSix" class="collapse show" data-parent="#accordionExample">
                    <div class="card-body">
                        <div class="shop__sidebar__tags">
                            <a href="#">Product</a>
                            <a href="#">Bags</a>
                            <a href="#">Shoes</a>
                            <a href="#">Fashio</a>
                            <a href="#">Clothing</a>
                            <a href="#">Hats</a>
                            <a href="#">Accessories</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>