blog/urls.py
from django.urls import path

from blog.views import BlogListView, BlogDetailView, CommentCreateView

app_name = 'blog'

urlpatterns = [
    path('<int:pk>/', BlogDetailView.as_view(), name='detail'),
    path('<int:pk>/comment/', CommentCreateView.as_view(), name='comment'),
    path('', BlogListView.as_view(), name='list'),
]

pages/urls.py
from django.urls import path

from pages.views import ContactCreateView, IndexTemplateView, AboutTemplateView

app_name = 'pages'

urlpatterns = [
    path('contact/', ContactCreateView.as_view(), name='contact'),
    path('about/', AboutTemplateView.as_view(), name='about'),
    path('', IndexTemplateView.as_view(), name='home'),
]

shop4/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path('products/', include('products.urls', namespace='products')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('', include('pages.urls', namespace='pages')),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blog/models.py
from django.db import models
from django.utils.translation import gettext as _


class AuthorModel(models.Model):
    full_name = models.CharField(max_length=64, verbose_name=_('full name'))
    avatar = models.ImageField(upload_to='author-avatar', verbose_name=_('avatar'))

    created_at = models.DateTimeField(auto_now_add=True, verbose_name=_('created_at'))

    def __str__(self):
        return self.full_name

    class Meta:
        verbose_name = _('author')
        verbose_name_plural = _('authors')


class PostTagModel(models.Model):
    title = models.CharField(max_length=32, verbose_name=_('title'))
    created_at = models.DateTimeField(auto_now_add=True, verbose_name=_('created_at'))

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = _('post tag')
        verbose_name_plural = _('post tags')


class PostModel(models.Model):
    title = models.CharField(max_length=255, verbose_name=_('title'))
    image = models.ImageField(upload_to='posts', verbose_name=_('images'))
    banner = models.ImageField(upload_to='post-banner', verbose_name=_('banner'))
    author = models.ForeignKey(AuthorModel, related_name='posts', on_delete=models.PROTECT, verbose_name=_('author'))

    tags = models.ManyToManyField(PostTagModel, related_name='posts', verbose_name=_('tags'))

    content = models.TextField(verbose_name=_('content'))

    created_at = models.DateTimeField(auto_now_add=True, verbose_name=_('created_at'))

    def __str__(self):
        return self.title

    # def get_next_post(self):
    #     return self.get_next_by_created_at()
    #
    # def get_prev_post(self):
    #     return self.get_previous_by_created_at()

    class Meta:
        verbose_name = _('post')
        verbose_name_plural = _('posts')


class CommentModel(models.Model):
    post = models.ForeignKey(
        PostModel,
        related_name='comments',
        on_delete=models.CASCADE,
        verbose_name=_('post'))

    name = models.CharField(max_length=64, verbose_name=_('name'))
    email = models.EmailField(verbose_name=_('email'))
    phone = models.CharField(max_length=13, verbose_name=_('phone'))
    message = models.TextField(verbose_name=_('message'))

    created_at = models.DateTimeField(auto_now_add=True, verbose_name=_('created_at'))

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _('comment')
        verbose_name_plural = _('comments')

blog/forms.py
from django import forms

from blog.models import CommentModel


class CommentModelForm(forms.ModelForm):
    class Meta:
        model = CommentModel
        exclude = ['post', 'created_at']

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from django.views.generic import TemplateView, ListView, DetailView, CreateView

from blog.forms import CommentModelForm
from blog.models import PostModel


class BlogListView(ListView):
    template_name = 'blog.html'
    paginate_by = 2

    def get_queryset(self):
        qs = PostModel.objects.order_by('-pk')
        tag = self.request.GET.get('tag')

        if tag:
            qs = qs.filter(tags__title=tag)
        return qs


class BlogDetailView(DetailView):
    template_name = 'blog-detail.html'
    model = PostModel


class CommentCreateView(CreateView):
    form_class = CommentModelForm

    def form_valid(self, form):
        form.instance.post = get_object_or_404(PostModel, pk=self.kwargs.get('pk'))
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('blog:detail', kwargs={'pk': self.kwargs.get('pk')})

templates/blog-detail.html
{% extends 'layouts/base.html' %}
{% load static %}

{% block content %}
    <!-- Blog Details Hero Begin -->
    <section class="blog-hero spad">
        <div class="container">
            <div class="row d-flex justify-content-center">
                <div class="col-lg-9 text-center">
                    <div class="blog__hero__text">
                        <h2>{{ object.title }}</h2>
                        <ul>
                            <li>By {{ object.author }}</li>
                            <li>{{ object.created_at|date:'N d, Y' }}</li>
                            <li>8 Comments</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Blog Details Hero End -->

    <!-- Blog Details Section Begin -->
    <section class="blog-details spad">
        <div class="container">
            <div class="row d-flex justify-content-center">
                <div class="col-lg-12">
                    <div class="blog__details__pic">
                        <img src="{{ object.banner.url }}" alt="">
                    </div>
                </div>
                <div class="col-lg-8">
                    <div class="blog__details__content">
                        <div class="blog__details__share">
                            <span>share</span>
                            <ul>
                                <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                                <li><a href="#" class="twitter"><i class="fa fa-twitter"></i></a></li>
                                <li><a href="#" class="youtube"><i class="fa fa-youtube-play"></i></a></li>
                                <li><a href="#" class="linkedin"><i class="fa fa-linkedin"></i></a></li>
                            </ul>
                        </div>
                        <div class="blog__details__text">
                            {{ object.content }}
                        </div>
                        <div class="blog__details__text">
                            <p>Vyo-Serum along with tightening the skin also reduces the fine lines indicating aging of
                                skin. Problems like dark circles, puffiness, and crow’s feet can be control from the
                                strong effects of this serum.</p>
                            <p>Hydroderm is a multi-functional product that helps in reducing the cellulite and giving
                                the body a toned shape, also helps in cleansing the skin from the root and not letting
                                the pores clog, nevertheless also let’s sweeps out the wrinkles and all signs of aging
                                from the sensitive near the eyes.</p>
                        </div>
                        <div class="blog__details__option">
                            <div class="row">
                                <div class="col-lg-6 col-md-6 col-sm-6">
                                    <div class="blog__details__author">
                                        <div class="blog__details__author__pic">
                                            <img src="{{ object.author.avatar.url }}" alt="">
                                        </div>
                                        <div class="blog__details__author__text">
                                            <h5>{{ object.author.full_name }}</h5>
                                        </div>
                                    </div>
                                </div>

                                <div class="col-lg-6 col-md-6 col-sm-6">
                                    <div class="blog__details__tags">
                                        {% for tag in object.tags.all %}
                                            <a href="{% url 'blog:list' %}?tag={{ tag.title }}">#{{ tag.title }}</a>
                                        {% endfor %}


                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="blog__details__btns">
                            <div class="row">

                                <div class="col-lg-6 col-md-6 col-sm-6">
                                    {% if object.get_previous_by_created_at %}
                                        <a href="{% url 'blog:detail' pk=object.get_previous_by_created_at.pk %}"
                                           class="blog__details__btns__item">
                                            <p><span class="arrow_left"></span> Previous Pod</p>
                                            <h5>{{ object.get_previous_by_created_at.title }}</h5>
                                        </a>
                                    {% endif %}
                                </div>
                                <div class="col-lg-6 col-md-6 col-sm-6">
                                    {% if object.get_next_by_created_at %}
                                        <a href="{% url 'blog:detail' pk=object.get_next_by_created_at.pk %}"
                                           class="blog__details__btns__item blog__details__btns__item--next">
                                            <p>Next Pod <span class="arrow_right"></span></p>
                                            <h5>{{ object.get_next_by_created_at.title }}</h5>
                                        </a>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                        <div id="comment-section" class="row">
                            <div class="col-md-12 col-sm-12">
                                <ul>
                                    {% for comment in object.commets.all %}
                                        <li class="media">
                                            <div class="media-body">
                                                <span class="text-muted pull-right">
                                                    <small class="text-muted">
                                                        {{ comment.created_at|timesince }}
                                                    </small>
                                                </span>
                                                <strong>{{ comment.name }}</strong>
                                                <p>
                                                    {{ comment.message }}
                                                </p>
                                            </div>
                                        </li>
                                    {% endfor %}
                                </ul>
                            </div>
                        </div>
                        <div class="blog__details__comment">
                            <h4>Leave A Comment</h4>
                            <form method="POST" action="{% url 'blog:comment' pk=object.pk %}">
                                {% csrf_token %}
                                <div class="row">
                                    <div class="col-lg-4 col-md-4">
                                        <input name="name" type="text" placeholder="Name">
                                    </div>
                                    <div class="col-lg-4 col-md-4">
                                        <input name="email" type="email" placeholder="Email">
                                    </div>
                                    <div class="col-lg-4 col-md-4">
                                        <input name="phone" type="text" placeholder="Phone">
                                    </div>
                                    <div class="col-lg-12 text-center">
                                        <textarea name="message" placeholder="Comment"></textarea>
                                        <button type="submit" class="site-btn">Post Comment</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Blog Details Section End -->

{% endblock %}

templates/blog.html
{% extends 'layouts/base.html' %}

{% load static %}

{% block content %}

    <section class="breadcrumb-blog set-bg" data-setbg="{% static 'img/breadcrumb-bg.jpg' %}">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <h2>
                        {% if request.GET.tag %}
                            #{{ request.GET.tag }}
                        {% else %}
                            Our blog
                        {% endif %}
                    </h2> {# should be changed for hashtags #}
                </div>
            </div>
        </div>
    </section>

    <section class="blog spad">
        <div class="container">
            <div class="row">
                {% for i in object_list %}

                    <div class="col-lg-4 col-md-6 col-sm-6">
                        <div class="blog__item">
                            <div class="blog__item__pic set-bg" data-setbg="{{ i.image.url }}"></div>
                            <div class="blog__item__text">
                                <span><img src="{% static 'img/icon/calendar.png' %}"
                                           alt="">{{ i.created_at|date:'d N Y' }}</span>
                                <h5>{{ post.title }}</h5>
                                <a href="{% url 'blog:detail' pk=i.pk %}">Read More</a>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>

            {{ page_obj }}

            <div class="row">
                <div class="col-lg-12">
                    <div class="product__pagination">
                        {#                        {% if page_obj.has_previous %}#}
                        {#                            <a href="?page={{ page }}"> < </a>#}
                        {#                        {% endif %}#}
                        {#                        {% if page_obj.has_next %}#}
                        {#                            <a href="?page={{ page }}"> > </a>#}
                        {#                        {% endif %}#}

                        {% for page in page_obj.paginator.page_range %}
                            <a {% if page == page_obj.number %}
                                class="active" {% endif %} href="?page={{ page }}">{{ page }}</a>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </section>

{% endblock %}

templates/shop-details.html
{% extends 'layouts/base.html' %}
{% load static %}
{% block content %}

    <section class="shop-details">
        <div class="product__details__pic">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="product__details__breadcrumb">
                            <a href="{% url 'pages:home' %}">Home</a>
                            <a href="{% url 'products:list' %}">Shop</a>
                            <span>{{ object.title }} </span>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-3 col-md-3">
                        <ul class="nav nav-tabs" role="tablist">
                            <li class="nav-item">
                                <a class="nav-link active" data-toggle="tab" href="#tabs-1" role="tab">
                                    <div class="product__thumb__pic set-bg" data-setbg="img/shop-details/thumb-1.png">
                                    </div>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" data-toggle="tab" href="#tabs-2" role="tab">
                                    <div class="product__thumb__pic set-bg" data-setbg="img/shop-details/thumb-2.png">
                                    </div>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" data-toggle="tab" href="#tabs-3" role="tab">
                                    <div class="product__thumb__pic set-bg" data-setbg="img/shop-details/thumb-3.png">
                                    </div>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" data-toggle="tab" href="#tabs-4" role="tab">
                                    <div class="product__thumb__pic set-bg" data-setbg="img/shop-details/thumb-4.png">
                                        <i class="fa fa-play"></i>
                                    </div>
                                </a>
                            </li>
                        </ul>
                    </div>
                    <div class="col-lg-6 col-md-9">
                        <div class="tab-content">
                            <div class="tab-pane active" id="tabs-1" role="tabpanel">
                                <div class="product__details__pic__item">
                                    <img src="img/shop-details/product-big-2.png" alt="">
                                </div>
                            </div>
                            <div class="tab-pane" id="tabs-2" role="tabpanel">
                                <div class="product__details__pic__item">
                                    <img src="img/shop-details/product-big-3.png" alt="">
                                </div>
                            </div>
                            <div class="tab-pane" id="tabs-3" role="tabpanel">
                                <div class="product__details__pic__item">
                                    <img src="img/shop-details/product-big.png" alt="">
                                </div>
                            </div>
                            <div class="tab-pane" id="tabs-4" role="tabpanel">
                                <div class="product__details__pic__item">
                                    <img src="img/shop-details/product-big-4.png" alt="">
                                    <a href="https://www.youtube.com/watch?v=8PJ3_p7VqHw&list=RD8PJ3_p7VqHw&start_radio=1"
                                       class="video-popup"><i class="fa fa-play"></i></a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="product__details__content">
            <div class="container">
                <div class="row d-flex justify-content-center">
                    <div class="col-lg-8">
                        <div class="product__details__text">
                            <h4>{{ object.title }}</h4>
                            <div class="rating">
                                <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i>
                                <i class="fa fa-star-o"></i>
                                <span> - 5 Reviews</span>
                            </div>
                            <h3>{{ object.get_price }} {% if object.is_discount %}
                                <span>{{ object.price }}</span>{% endif %}</h3>
                            <p>{{ object.short_description }}</p>
                            <div class="product__details__option">
                                <div class="product__details__option__size">
                                    <span>Size:</span>
                                    <label for="xxl">xxl
                                        <input type="radio" id="xxl">
                                    </label>
                                    <label class="active" for="xl">xl
                                        <input type="radio" id="xl">
                                    </label>
                                    <label for="l">l
                                        <input type="radio" id="l">
                                    </label>
                                    <label for="sm">s
                                        <input type="radio" id="sm">
                                    </label>
                                </div>
                                <div class="product__details__option__color">
                                    <span>Color:</span>
                                    <label class="c-1" for="sp-1">
                                        <input type="radio" id="sp-1">
                                    </label>
                                    <label class="c-2" for="sp-2">
                                        <input type="radio" id="sp-2">
                                    </label>
                                    <label class="c-3" for="sp-3">
                                        <input type="radio" id="sp-3">
                                    </label>
                                    <label class="c-4" for="sp-4">
                                        <input type="radio" id="sp-4">
                                    </label>
                                    <label class="c-9" for="sp-9">
                                        <input type="radio" id="sp-9">
                                    </label>
                                </div>
                            </div>
                            <div class="product__details__cart__option">
                                <div class="quantity">
                                    <div class="pro-qty">
                                        <input type="text" value="1">
                                    </div>
                                </div>
                                <a href="#" class="primary-btn">add to cart</a>
                            </div>
                            <div class="product__details__btns__option">
                                <a href="#"><i class="fa fa-heart"></i> add to wishlist</a>
                                <a href="#"><i class="fa fa-exchange"></i> Add To Compare</a>
                            </div>
                            <div class="product__details__last__option">
                                <h5><span>Guaranteed Safe Checkout</span></h5>
                                <img src="img/shop-details/details-payment.png" alt="">
                                <ul>
                                    <li><span>SKU:</span> 3812912</li>
                                    <li><span>Category:</span> {{ object.category.title }}</li>
                                    <li><span>Tag:</span> {% for tag in object.tags.all %}&nbsp#{{ tag.title }}{% endfor %}
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-12">
                        <div class="product__details__tab">
                            <ul class="nav nav-tabs" role="tablist">
                                <li class="nav-item">
                                    <a class="nav-link active" data-toggle="tab" href="#tabs-5"
                                       role="tab">Description</a>
                                </li>
                            </ul>
                            <div class="tab-content">
                                <div class="tab-pane active" id="tabs-5" role="tabpanel">
                                    <div class="product__details__tab__content">
                                        <p class="note">{{ object.long_description }}</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section class="related spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <h3 class="related-title">Related Product</h3>
                </div>
            </div>
            <div class="row">
                {% for product in object.get_related %}
                    <div class="col-lg-3 col-md-6 col-sm-6 col-sm-6">
                        {% include 'layouts/product_block.html' %}
                    </div>
                {% endfor %}
            </div>
        </div>
    </section>
{% endblock %}

templates/shop.html
{% extends 'layouts/base.html' %}
{% load static %}
{% block content %}
    <section class="breadcrumb-option">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="breadcrumb__text">
                        <h4>Shop</h4>
                        <div class="breadcrumb__links">
                            <a href="{% url 'pages:home' %}">Home</a>
                            <span>Shop</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section class="shop spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-3">
                    {% include 'layouts/shop_filter.html' %}
                </div>
                <div class="col-lg-9">
                    <div class="shop__product__option">
                        <div class="row">
                            <div class="col-lg-6 col-md-6 col-sm-6">
                                <div class="shop__product__option__left">
                                    <p>Showing {{ page_obj.start_index }}-{{ page_obj.end_index }}
                                        of {{ page_obj.paginator.count }}</p>
                                </div>
                            </div>
                            <div class="col-lg-6 col-md-6 col-sm-6">
                                <div class="shop__product__option__right">
                                    <p>Sort by Price:</p>
                                    <select>
                                        <option value="">---</option>
                                        <option value="">Low To High</option>
                                        <option value="">High To Low</option>

                                    </select>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">

                        {% for product in object_list %}
                            <div class="col-lg-4 col-md-6 col-sm-6">
                                {% include 'layouts/product_block.html' %}
                            </div>

                        {% endfor %}
                    </div>
                    <div class="product__pagination">
                        {#                        {% if page_obj.has_previous %}#}
                        {#                            <a href="?page={{ page }}"> < </a>#}
                        {#                        {% endif %}#}
                        {#                        {% if page_obj.has_next %}#}
                        {#                            <a href="?page={{ page }}"> > </a>#}
                        {#                        {% endif %}#}

                        {% for page in page_obj.paginator.page_range %}
                            <a {% if page == page_obj.number %}
                                class="active" {% endif %} href="?page={{ page }}">{{ page }}</a>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </section>

{% endblock %}